<?php

namespace App\Task;

use App\Model\ProofRecord;
use SilverStripe\Dev\BuildTask;

/**
 * Drives SilverStripe's ORM through a write/read/aggregate cycle.
 *
 * Every statement this task causes is generated by SilverStripe's stock
 * MySQL/MariaDB driver and answered by PostgreSQL via the middleware.
 */
class ProofTask extends BuildTask
{
    private static $segment = 'mysql2pg-proof';

    protected $title = 'mysql2pg middleware proof';

    protected $description = 'Creates, queries and aggregates ProofRecord rows through the ORM.';

    public function run($request)
    {
        foreach (ProofRecord::get() as $existing) {
            $existing->delete();
        }

        $seed = [
            ['Widget', 3, '19.99', true,  'first note'],
            ['Gadget', 10, '5.50', false, 'second note'],
            ['Doohickey', 7, '101.25', true, 'third note'],
        ];
        foreach ($seed as [$title, $qty, $price, $active, $notes]) {
            $record = ProofRecord::create();
            $record->Title = $title;
            $record->Quantity = $qty;
            $record->Price = $price;
            $record->Active = $active;
            $record->Notes = $notes;
            $record->PublishedAt = '2026-09-20 12:00:00';
            $record->write();
        }

        $total = ProofRecord::get()->count();
        $active = ProofRecord::get()->filter('Active', true)->count();
        $sum = ProofRecord::get()->sum('Quantity');
        $max = ProofRecord::get()->max('Price');
        $sorted = ProofRecord::get()->sort('Quantity DESC')->first();
        $found = ProofRecord::get()->filter('Title:PartialMatch', 'adge')->first();

        // Update + re-read, so UPDATE and the write-through path are covered.
        $sorted->Quantity = 99;
        $sorted->write();
        $reread = ProofRecord::get()->byID($sorted->ID);

        printf("PROOF total=%d active=%d sum_qty=%s max_price=%s top=%s partial=%s updated=%d\n",
            $total, $active, $sum, $max, $sorted->Title, $found ? $found->Title : 'none', $reread->Quantity);
    }
}
