<?php

namespace BookStack\Console\Commands;

use BookStack\Entities\Models\Book;
use BookStack\Entities\Models\Chapter;
use BookStack\Entities\Models\Page;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

/**
 * Drives BookStack's Eloquent models through a write/read/aggregate cycle.
 *
 * Every statement this produces is generated by Laravel's MySQL grammar and
 * answered by PostgreSQL via the middleware.
 */
class Mysql2pgProof extends Command
{
    protected $signature = 'mysql2pg:proof';

    protected $description = 'Creates, queries and aggregates BookStack entities through Eloquent';

    public function handle(): int
    {
        Page::query()->where('name', 'like', 'mysql2pg%')->forceDelete();
        Chapter::query()->where('name', 'like', 'mysql2pg%')->forceDelete();
        Book::query()->where('name', 'like', 'mysql2pg%')->forceDelete();

        $book = Book::query()->make([
            'name'        => 'mysql2pg book',
            'slug'        => 'mysql2pg-book',
            'description' => 'written through the middleware',
        ]);
        $book->save();

        $chapter = Chapter::query()->make([
            'name'     => 'mysql2pg chapter',
            'slug'     => 'mysql2pg-chapter',
            'book_id'  => $book->id,
            'priority' => 1,
        ]);
        $chapter->save();

        foreach ([['mysql2pg page one', 10], ['mysql2pg page two', 20], ['mysql2pg page three', 30]] as [$name, $priority]) {
            $page = Page::query()->make([
                'name'       => $name,
                'slug'       => str_replace(' ', '-', $name),
                'book_id'    => $book->id,
                'chapter_id' => $chapter->id,
                'priority'   => $priority,
                'html'       => '<p>body</p>',
                'text'       => 'body',
            ]);
            $page->save();
        }

        $pages     = Page::query()->where('book_id', $book->id);
        $total     = $pages->count();
        $sum       = (int) Page::query()->where('book_id', $book->id)->sum('priority');
        $max       = (int) Page::query()->where('book_id', $book->id)->max('priority');
        $ordered   = Page::query()->where('book_id', $book->id)->orderByDesc('priority')->first();
        $partial   = Page::query()->where('name', 'like', '%page two%')->first();

        // Update then re-read, so UPDATE and the read-back path are both covered.
        $ordered->priority = 99;
        $ordered->save();
        $reread = Page::query()->find($ordered->id);

        // A join and a group-by, which is where dialect differences usually bite.
        $grouped = DB::table('pages')
            ->join('books', 'books.id', '=', 'pages.book_id')
            ->where('books.id', $book->id)
            ->groupBy('books.name')
            ->selectRaw('books.name as book_name, count(*) as page_count')
            ->first();

        $this->line(sprintf(
            'PROOF book=%s pages=%d sum_priority=%d max_priority=%d top=%s partial=%s updated=%d grouped=%s/%d',
            $book->slug,
            $total,
            $sum,
            $max,
            $ordered->name,
            $partial ? $partial->name : 'none',
            $reread->priority,
            $grouped->book_name ?? 'none',
            $grouped->page_count ?? 0
        ));

        return self::SUCCESS;
    }
}
