use mysql2pg_middleware::{config::TranslatorConfig, translator::translate_sql};

#[test]
fn select_translation_smoke() {
    let sql = "SELECT `id`, IFNULL(`name`, 'n/a') FROM `users` LIMIT 0, 5";
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("\"id\""));
    assert!(result.translated_sql.contains("COALESCE"));
    assert!(result.translated_sql.contains("LIMIT 5 OFFSET 0"));
}

#[test]
fn unsupported_mysql_constructs_fail_fast() {
    let sql = "INSERT INTO users(id, name) VALUES (1, 'a') ON DUPLICATE KEY UPDATE name='b'";
    let err = translate_sql(sql, &TranslatorConfig::default()).unwrap_err();
    assert!(err.to_string().contains("ON DUPLICATE KEY UPDATE"));
}

#[test]
fn create_table_type_mappings_translation_smoke() {
    let sql = r#"
        CREATE TABLE metrics (
            id INT NOT NULL AUTO_INCREMENT,
            tiny_value TINYINT,
            medium_value MEDIUMINT,
            small_unsigned SMALLINT UNSIGNED,
            amount DECIMAL(12, 4) UNSIGNED,
            ratio FLOAT,
            score DOUBLE,
            payload JSON,
            flags SET('new', 'sale'),
            notes MEDIUMTEXT,
            raw_data LONGBLOB,
            happened_at DATETIME(6),
            touched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    "#;

    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();

    assert!(result.translated_sql.contains("id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY"));
    assert!(result.translated_sql.contains("tiny_value SMALLINT"));
    assert!(result.translated_sql.contains("medium_value INTEGER"));
    assert!(result.translated_sql.contains("small_unsigned INTEGER"));
    assert!(result.translated_sql.contains("amount NUMERIC(12,4)"));
    assert!(result.translated_sql.contains("ratio REAL"));
    assert!(result.translated_sql.contains("score DOUBLE PRECISION"));
    assert!(result.translated_sql.contains("payload JSONB"));
    assert!(result.translated_sql.contains("flags TEXT"));
    assert!(result.translated_sql.contains("notes TEXT"));
    assert!(result.translated_sql.contains("raw_data BYTEA"));
    assert!(result.translated_sql.contains("happened_at TIMESTAMP(6)"));
    assert!(!result.translated_sql.contains("ON UPDATE CURRENT_TIMESTAMP"));
    assert!(!result.translated_sql.contains("ENGINE"));
}

#[test]
fn show_tables_translation_smoke() {
    let result = translate_sql("SHOW TABLES LIKE 'ord%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("FROM information_schema.tables"));
    assert!(result.translated_sql.contains("table_schema = current_schema()"));
    assert!(result.translated_sql.contains("table_name LIKE 'ord%'"));
    assert!(result.translated_sql.contains("AS \"Tables_in_current_schema\""));
}
