use mysql2pg_middleware::{config::TranslatorConfig, translator::translate_sql};

#[test]
fn select_translation_smoke() {
    let sql = "SELECT `id`, IFNULL(`name`, 'n/a') FROM `users` LIMIT 0, 5";
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("\"id\""));
    assert!(result.translated_sql.contains("COALESCE"));
    assert!(result.translated_sql.contains("LIMIT 5 OFFSET 0"));
}

#[test]
fn unsupported_mysql_constructs_fail_fast() {
    let sql = "INSERT INTO users(id, name) VALUES (1, 'a') ON DUPLICATE KEY UPDATE name='b'";
    let err = translate_sql(sql, &TranslatorConfig::default()).unwrap_err();
    assert!(err.to_string().contains("ON DUPLICATE KEY UPDATE"));
}

#[test]
fn insert_ignore_translation_smoke() {
    let sql = "INSERT IGNORE INTO `option` (option_name, option_value, autoload) VALUES ('a', 'b', 'c')";
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result
        .translated_sql
        .contains("INSERT INTO \"option\" (option_name, option_value, autoload) VALUES ('a', 'b', 'c') ON CONFLICT DO NOTHING"));
}

#[test]
fn create_table_type_mappings_translation_smoke() {
    let sql = r#"
        CREATE TABLE metrics (
            id INT NOT NULL AUTO_INCREMENT,
            tiny_value TINYINT,
            medium_value MEDIUMINT,
            small_unsigned SMALLINT UNSIGNED,
            amount DECIMAL(12, 4) UNSIGNED,
            ratio FLOAT,
            score DOUBLE,
            payload JSON,
            flags SET('new', 'sale'),
            notes MEDIUMTEXT,
            raw_data LONGBLOB,
            happened_at DATETIME(6),
            touched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    "#;

    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();

    assert!(result.translated_sql.contains("\"id\" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY"));
    assert!(result.translated_sql.contains("\"tiny_value\" SMALLINT"));
    assert!(result.translated_sql.contains("\"medium_value\" INTEGER"));
    assert!(result.translated_sql.contains("\"small_unsigned\" INTEGER"));
    assert!(result.translated_sql.contains("\"amount\" NUMERIC(12,4)"));
    assert!(result.translated_sql.contains("\"ratio\" REAL"));
    assert!(result.translated_sql.contains("\"score\" DOUBLE PRECISION"));
    assert!(result.translated_sql.contains("\"payload\" JSONB"));
    assert!(result.translated_sql.contains("\"flags\" TEXT"));
    assert!(result.translated_sql.contains("\"notes\" TEXT"));
    assert!(result.translated_sql.contains("\"raw_data\" BYTEA"));
    assert!(result.translated_sql.contains("\"happened_at\" TIMESTAMP(6)"));
    assert!(!result.translated_sql.contains("ON UPDATE CURRENT_TIMESTAMP"));
    assert!(!result.translated_sql.contains("ENGINE"));
}

#[test]
fn show_tables_translation_smoke() {
    let result = translate_sql("SHOW TABLES LIKE 'ord%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("FROM information_schema.tables"));
    assert!(result.translated_sql.contains("table_schema = current_schema()"));
    assert!(result.translated_sql.contains("table_name LIKE 'ord%'"));
    assert!(result.translated_sql.contains("AS \"Tables_in_current_schema\""));
}

#[test]
fn describe_table_translation_smoke() {
    let result = translate_sql("DESC order_details", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("AS \"Field\""));
    assert!(result.translated_sql.contains("AS \"Type\""));
    assert!(result.translated_sql.contains("AS \"Null\""));
    assert!(result.translated_sql.contains("AS \"Key\""));
    assert!(result.translated_sql.contains("AS \"Default\""));
    assert!(result.translated_sql.contains("AS \"Extra\""));
    assert!(result.translated_sql.contains("WHERE c.table_schema = 'public' AND c.table_name = 'order_details'"));
}

#[test]
fn show_databases_translation_smoke() {
    let result = translate_sql("SHOW DATABASES LIKE 'ap%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("FROM pg_database"));
    assert!(result.translated_sql.contains("datistemplate = FALSE"));
    assert!(result.translated_sql.contains("datname LIKE 'ap%'"));
    assert!(result.translated_sql.contains("AS \"Database\""));
}

#[test]
fn show_columns_translation_smoke() {
    let result = translate_sql("SHOW COLUMNS FROM order_details LIKE 'order%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("AS \"Field\""));
    assert!(result.translated_sql.contains("c.table_name = 'order_details'"));
    assert!(result.translated_sql.contains("c.column_name LIKE 'order%'"));
}

#[test]
fn show_create_table_translation_smoke() {
    let result = translate_sql("SHOW CREATE TABLE order_details", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("AS \"Create Table\""));
    assert!(result.translated_sql.contains("pg_constraint"));
    assert!(result.translated_sql.contains("CREATE TABLE %I"));
}

#[test]
fn show_variables_translation_smoke() {
    let result = translate_sql("SHOW VARIABLES LIKE 'version%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("\"Variable_name\""));
    assert!(result.translated_sql.contains("\"Value\""));
    assert!(result.translated_sql.contains("version_comment"));
    assert!(result.translated_sql.contains("\"Variable_name\" LIKE 'version%'"));
}

#[test]
fn show_status_translation_smoke() {
    let result = translate_sql("SHOW STATUS LIKE 'Threads%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("pg_stat_activity"));
    assert!(result.translated_sql.contains("\"Variable_name\" LIKE 'Threads%'"));
}

#[test]
fn show_collation_translation_smoke() {
    let result = translate_sql("SHOW COLLATION LIKE 'utf8%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("utf8mb4_unicode_ci"));
    assert!(result.translated_sql.contains("collation_rows(\"Collation\""));
    assert!(result.translated_sql.contains("\"Collation\" LIKE 'utf8%'"));
}

#[test]
fn show_charset_translation_smoke() {
    let result = translate_sql("SHOW CHARSET LIKE 'utf8%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("utf8mb4"));
    assert!(result.translated_sql.contains("AS charset_rows"));
    assert!(result.translated_sql.contains("\"Charset\" LIKE 'utf8%'"));
}

#[test]
fn show_views_translation_smoke() {
    let result = translate_sql("SHOW VIEWS", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("FROM information_schema.views"));
    assert!(result.translated_sql.contains("AS \"Tables_in_current_schema\""));
}

#[test]
fn create_table_with_inline_key_translation_smoke() {
    let sql = r#"
        CREATE TABLE piwik_test_table (
            id INT AUTO_INCREMENT,
            value INT,
            PRIMARY KEY (id),
            KEY index_value (value)
        )
    "#;
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("CREATE TABLE \"piwik_test_table\""));
    assert!(result.translated_sql.contains("GENERATED BY DEFAULT AS IDENTITY"));
    assert!(result.translated_sql.contains("CREATE INDEX \"piwik_test_table_index_value\" ON \"piwik_test_table\" (\"value\")"));
}

#[test]
fn create_table_with_desc_inline_key_translation_smoke() {
    let sql = r#"
        CREATE TABLE log_visit (
            idvisit BIGINT,
            idsite INT,
            config_id VARBINARY(16),
            visit_last_action_time DATETIME,
            idvisitor VARBINARY(8),
            KEY index_idsite_config_datetime (idsite, config_id, visit_last_action_time),
            KEY index_idsite_datetime (idsite, visit_last_action_time),
            KEY index_idsite_idvisitor_time (idsite, idvisitor, visit_last_action_time DESC)
        )
    "#;
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains(
        "CREATE INDEX \"log_visit_index_idsite_idvisitor_time\" ON \"log_visit\" (\"idsite\", \"idvisitor\", \"visit_last_action_time\" DESC)"
    ));
}

#[test]
fn create_table_with_unique_prefix_key_translation_smoke() {
    let sql = r#"
        CREATE TABLE log_profiling (
            query TEXT NOT NULL,
            count INTEGER UNSIGNED NULL,
            sum_time_ms FLOAT NULL,
            idprofiling BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            PRIMARY KEY (idprofiling),
            UNIQUE KEY query(query(100))
        )
    "#;
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("CREATE TABLE \"log_profiling\""));
    assert!(result
        .translated_sql
        .contains("CREATE UNIQUE INDEX \"log_profiling_query\" ON \"log_profiling\" ((left(\"query\", 100)))"));
}

#[test]
fn create_temporary_table_translation_smoke() {
    let sql = r#"
        CREATE TEMPORARY TABLE piwik_test_table_temp (
            id INT AUTO_INCREMENT,
            PRIMARY KEY (id)
        )
    "#;
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("CREATE TEMPORARY TABLE \"piwik_test_table_temp\""));
    assert!(result.translated_sql.contains("GENERATED BY DEFAULT AS IDENTITY"));
}
