use mysql2pg_middleware::{config::TranslatorConfig, translator::translate_sql};

#[test]
fn select_translation_smoke() {
    let sql = "SELECT `id`, IFNULL(`name`, 'n/a') FROM `users` LIMIT 0, 5";
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("\"id\""));
    assert!(result.translated_sql.contains("COALESCE"));
    assert!(result.translated_sql.contains("LIMIT 5 OFFSET 0"));
}

#[test]
fn sql_no_cache_select_modifier_translation_smoke() {
    let sql = "SELECT SQL_NO_CACHE `value` FROM `matomo_locks` WHERE `key` = 'UsersManager.changePermissions' AND UNIX_TIMESTAMP() <= expiry_time LIMIT 1";
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();

    assert!(result.translated_sql.starts_with("SELECT \"value\" FROM \"matomo_locks\""));
    assert!(result
        .translated_sql
        .contains("EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) <= expiry_time"));
    assert!(!result.translated_sql.contains("SQL_NO_CACHE"));
}

#[test]
fn on_duplicate_key_update_translation_smoke() {
    let sql = "INSERT INTO user_language (login, language) VALUES (?, ?) ON DUPLICATE KEY UPDATE language = ?";
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result
        .translated_sql
        .contains("INSERT INTO \"user_language\" (\"login\", \"language\") VALUES (?, ?) ON CONFLICT (\"login\") DO UPDATE SET \"language\" = ?"));
}

#[test]
fn on_duplicate_key_update_adds_user_language_default_for_prefixed_matomo_table() {
    let sql = "INSERT INTO matomo_user_language (login, use_12_hour_clock) VALUES ('root','0') ON DUPLICATE KEY UPDATE use_12_hour_clock='0'";
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();

    assert!(result.translated_sql.contains(
        "INSERT INTO \"matomo_user_language\" (\"login\", \"use_12_hour_clock\", \"language\") VALUES ('root', '0', '')"
    ));
    assert!(result
        .translated_sql
        .contains("ON CONFLICT (\"login\") DO UPDATE SET \"use_12_hour_clock\" = '0'"));
}

#[test]
fn on_duplicate_key_update_normalizes_mysql_escaped_string_literals() {
    let sql = r#"INSERT INTO matomo_session (id, modified, lifetime, data) VALUES ('abc', '1780099497', '1209600', 'a:1:{s:4:\"data\";s:5:\"hello\";}') ON DUPLICATE KEY UPDATE modified = '1780099497', lifetime = '1209600', data = 'a:1:{s:4:\"data\";s:5:\"hello\";}'"#;
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();

    assert!(result
        .translated_sql
        .contains("'a:1:{s:4:\"data\";s:5:\"hello\";}'"));
    assert!(!result.translated_sql.contains(r#"\"data\""#));
    assert!(result
        .translated_sql
        .contains("ON CONFLICT (\"id\") DO UPDATE SET"));
}

#[test]
fn on_duplicate_key_update_keeps_escaped_literal_commas_in_one_value() {
    let sql = r#"INSERT INTO matomo_session (id, data) VALUES ('abc', 'can\'t, split') ON DUPLICATE KEY UPDATE data = 'can\'t, split'"#;
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();

    assert!(result.translated_sql.contains("'can''t, split'"));
    assert!(result
        .translated_sql
        .contains("ON CONFLICT (\"id\") DO UPDATE SET"));
}

#[test]
fn insert_ignore_translation_smoke() {
    let sql = "INSERT IGNORE INTO `option` (option_name, option_value, autoload) VALUES ('a', 'b', 'c')";
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result
        .translated_sql
        .contains("INSERT INTO \"option\" (option_name, option_value, autoload) VALUES ('a', 'b', 'c') ON CONFLICT DO NOTHING"));
}

#[test]
fn create_table_type_mappings_translation_smoke() {
    let sql = r#"
        CREATE TABLE metrics (
            id INT NOT NULL AUTO_INCREMENT,
            tiny_value TINYINT,
            medium_value MEDIUMINT,
            small_unsigned SMALLINT UNSIGNED,
            amount DECIMAL(12, 4) UNSIGNED,
            ratio FLOAT,
            score DOUBLE,
            payload JSON,
            flags SET('new', 'sale'),
            notes MEDIUMTEXT,
            raw_data LONGBLOB,
            happened_at DATETIME(6),
            touched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            PRIMARY KEY (id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    "#;

    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();

    assert!(result.translated_sql.contains("\"id\" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY"));
    assert!(result.translated_sql.contains("\"tiny_value\" SMALLINT"));
    assert!(result.translated_sql.contains("\"medium_value\" INTEGER"));
    assert!(result.translated_sql.contains("\"small_unsigned\" INTEGER"));
    assert!(result.translated_sql.contains("\"amount\" NUMERIC(12,4)"));
    assert!(result.translated_sql.contains("\"ratio\" REAL"));
    assert!(result.translated_sql.contains("\"score\" DOUBLE PRECISION"));
    assert!(result.translated_sql.contains("\"payload\" JSONB"));
    assert!(result.translated_sql.contains("\"flags\" TEXT"));
    assert!(result.translated_sql.contains("\"notes\" TEXT"));
    assert!(result.translated_sql.contains("\"raw_data\" BYTEA"));
    assert!(result.translated_sql.contains("\"happened_at\" TIMESTAMP(6)"));
    assert!(!result.translated_sql.contains("ON UPDATE CURRENT_TIMESTAMP"));
    assert!(!result.translated_sql.contains("ENGINE"));
}

#[test]
fn show_tables_translation_smoke() {
    let result = translate_sql("SHOW TABLES LIKE 'ord%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("FROM information_schema.tables"));
    assert!(result.translated_sql.contains("table_schema = current_schema()"));
    assert!(result.translated_sql.contains("table_name LIKE 'ord%'"));
    assert!(result.translated_sql.contains("AS \"Tables_in_current_schema\""));
}

#[test]
fn describe_table_translation_smoke() {
    let result = translate_sql("DESC order_details", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("AS \"Field\""));
    assert!(result.translated_sql.contains("AS \"Type\""));
    assert!(result.translated_sql.contains("AS \"Null\""));
    assert!(result.translated_sql.contains("AS \"Key\""));
    assert!(result.translated_sql.contains("AS \"Default\""));
    assert!(result.translated_sql.contains("AS \"Extra\""));
    assert!(result.translated_sql.contains("WHERE c.table_schema = current_schema() AND c.table_name = 'order_details'"));
}

#[test]
fn show_databases_translation_smoke() {
    let result = translate_sql("SHOW DATABASES LIKE 'ap%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("FROM pg_database"));
    assert!(result.translated_sql.contains("datistemplate = FALSE"));
    assert!(result.translated_sql.contains("datname LIKE 'ap%'"));
    assert!(result.translated_sql.contains("AS \"Database\""));
}

#[test]
fn show_columns_translation_smoke() {
    let result = translate_sql("SHOW COLUMNS FROM order_details LIKE 'order%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("AS \"Field\""));
    assert!(result.translated_sql.contains("c.table_name = 'order_details'"));
    assert!(result.translated_sql.contains("c.column_name LIKE 'order%'"));
}

#[test]
fn show_create_table_translation_smoke() {
    let result = translate_sql("SHOW CREATE TABLE order_details", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("AS \"Create Table\""));
    assert!(result.translated_sql.contains("pg_constraint"));
    assert!(result.translated_sql.contains("CREATE TABLE %I"));
}

#[test]
fn show_variables_translation_smoke() {
    let result = translate_sql("SHOW VARIABLES LIKE 'version%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("\"Variable_name\""));
    assert!(result.translated_sql.contains("\"Value\""));
    assert!(result.translated_sql.contains("version_comment"));
    assert!(result.translated_sql.contains("\"Variable_name\" LIKE 'version%'"));
}

#[test]
fn mysql_system_variable_translation_smoke() {
    let result = translate_sql(
        "SELECT VERSION() AS version, CONCAT('[', @@sql_mode, ']') AS sql_mode, @@SESSION.version_comment AS comment",
        &TranslatorConfig::default(),
    )
    .unwrap();
    assert!(result.translated_sql.contains("'11.8.7-MariaDB-ubu2404'"));
    assert!(result.translated_sql.contains("'NO_AUTO_VALUE_ON_ZERO'"));
    assert!(result.translated_sql.contains("'MariaDB Server'"));
    assert!(!result.translated_sql.contains("@@sql_mode"));
}

#[test]
fn show_status_translation_smoke() {
    let result = translate_sql("SHOW STATUS LIKE 'Threads%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("pg_stat_activity"));
    assert!(result.translated_sql.contains("\"Variable_name\" LIKE 'Threads%'"));
}

#[test]
fn show_collation_translation_smoke() {
    let result = translate_sql("SHOW COLLATION LIKE 'utf8%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("utf8mb4_unicode_ci"));
    assert!(result.translated_sql.contains("collation_rows(\"Collation\""));
    assert!(result.translated_sql.contains("\"Collation\" LIKE 'utf8%'"));
}

#[test]
fn show_charset_translation_smoke() {
    let result = translate_sql("SHOW CHARSET LIKE 'utf8%'", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("utf8mb4"));
    assert!(result.translated_sql.contains("AS charset_rows"));
    assert!(result.translated_sql.contains("\"Charset\" LIKE 'utf8%'"));
}

#[test]
fn show_index_where_translation_smoke() {
    let result = translate_sql(
        "SHOW INDEX FROM `log_visit` WHERE Key_name = ?",
        &TranslatorConfig::default(),
    )
    .unwrap();
    assert!(result.translated_sql.contains("FROM pg_class cls"));
    assert!(result.translated_sql.contains("cls.relname = 'log_visit'"));
    assert!(result.translated_sql.contains("WHERE \"Key_name\" = $1"));
    assert!(result.translated_sql.contains("AS \"Key_name\""));
}

#[test]
fn show_views_translation_smoke() {
    let result = translate_sql("SHOW VIEWS", &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("FROM information_schema.views"));
    assert!(result.translated_sql.contains("AS \"Tables_in_current_schema\""));
}

#[test]
fn reserved_user_table_is_quoted_in_selects() {
    let result = translate_sql(
        "SELECT * FROM user WHERE login = ?",
        &TranslatorConfig::default(),
    )
    .unwrap();
    assert!(result.translated_sql.contains("FROM \"user\""));
    assert!(result.translated_sql.contains("WHERE login = ?"));
}

#[test]
fn create_table_with_inline_key_translation_smoke() {
    let sql = r#"
        CREATE TABLE piwik_test_table (
            id INT AUTO_INCREMENT,
            value INT,
            PRIMARY KEY (id),
            KEY index_value (value)
        )
    "#;
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("CREATE TABLE \"piwik_test_table\""));
    assert!(result.translated_sql.contains("GENERATED BY DEFAULT AS IDENTITY"));
    assert!(result.translated_sql.contains("CREATE INDEX \"piwik_test_table_index_value\" ON \"piwik_test_table\" (\"value\")"));
}

#[test]
fn alter_table_add_column_unsigned_translation_smoke() {
    let sql = "ALTER TABLE matomo_log_visit ADD COLUMN last_idlink_va BIGINT UNSIGNED DEFAULT NULL, ADD COLUMN custom_dimension_1 VARCHAR(255) DEFAULT NULL, ADD COLUMN custom_dimension_rank SMALLINT UNSIGNED DEFAULT 0;";
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();

    assert!(result.translated_sql.contains("ALTER TABLE \"matomo_log_visit\""));
    assert!(result
        .translated_sql
        .contains("ADD COLUMN \"last_idlink_va\" BIGINT DEFAULT NULL"));
    assert!(result
        .translated_sql
        .contains("ADD COLUMN \"custom_dimension_1\" VARCHAR(255) DEFAULT NULL"));
    assert!(result
        .translated_sql
        .contains("ADD COLUMN \"custom_dimension_rank\" INTEGER DEFAULT 0"));
    assert!(result
        .translated_sql
        .contains("ADD CHECK (custom_dimension_rank >= 0 AND custom_dimension_rank <= 65535)"));
    assert!(!result.translated_sql.contains("UNSIGNED"));
}

#[test]
fn alter_table_modify_column_unsigned_translation_smoke() {
    let sql = "ALTER TABLE `matomo_log_visit` MODIFY COLUMN `visitor_seconds_since_first` INT(11) UNSIGNED NULL, MODIFY COLUMN `visitor_count_visits` INT(11) UNSIGNED NOT NULL DEFAULT 0, MODIFY COLUMN `config_device_model` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;";
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();

    assert!(result.translated_sql.contains("ALTER TABLE \"matomo_log_visit\""));
    assert!(result
        .translated_sql
        .contains("ALTER COLUMN \"visitor_seconds_since_first\" TYPE BIGINT"));
    assert!(result
        .translated_sql
        .contains("ALTER COLUMN \"visitor_seconds_since_first\" DROP NOT NULL"));
    assert!(result
        .translated_sql
        .contains("ALTER COLUMN \"visitor_count_visits\" SET NOT NULL"));
    assert!(result
        .translated_sql
        .contains("ALTER COLUMN \"visitor_count_visits\" SET DEFAULT 0"));
    assert!(result
        .translated_sql
        .contains("ADD CHECK (visitor_count_visits >= 0 AND visitor_count_visits <= 4294967295)"));
    assert!(result
        .translated_sql
        .contains("ALTER COLUMN \"config_device_model\" TYPE VARCHAR(100)"));
    assert!(!result.translated_sql.contains("UNSIGNED"));
    assert!(!result.translated_sql.contains("CHARACTER SET"));
    assert!(!result.translated_sql.contains("COLLATE"));
}

#[test]
fn alter_table_add_index_translation_smoke() {
    let sql = "ALTER TABLE `matomo_log_link_visit_action` ADD COLUMN `server_time` DATETIME NOT NULL, ADD INDEX index_idsite_servertime ( idsite, server_time ), ADD COLUMN `idpageview` CHAR(6) NULL DEFAULT NULL, ADD COLUMN `idaction_name` INTEGER(10) UNSIGNED, ADD COLUMN `time_dom_completion` MEDIUMINT(10) UNSIGNED NULL;";
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();

    assert!(result
        .translated_sql
        .contains("ALTER TABLE \"matomo_log_link_visit_action\" ADD COLUMN \"server_time\" TIMESTAMP NOT NULL"));
    assert!(result
        .translated_sql
        .contains("ADD COLUMN \"idpageview\" CHAR(6) NULL DEFAULT NULL"));
    assert!(result
        .translated_sql
        .contains("ADD COLUMN \"idaction_name\" BIGINT"));
    assert!(result
        .translated_sql
        .contains("ADD CHECK (\"idaction_name\" >= 0 AND \"idaction_name\" <= 4294967295)"));
    assert!(result
        .translated_sql
        .contains("ADD CHECK (\"time_dom_completion\" >= 0 AND \"time_dom_completion\" <= 16777215)"));
    assert!(result.translated_sql.contains(
        "CREATE INDEX \"matomo_log_link_visit_action_index_idsite_servertime\" ON \"matomo_log_link_visit_action\" (\"idsite\", \"server_time\")"
    ));
    assert!(!result.translated_sql.contains("ADD INDEX"));
    assert!(!result.translated_sql.contains("UNSIGNED"));
}

#[test]
fn alter_table_drop_index_translation_smoke() {
    let sql = "ALTER TABLE `matomo_log_link_visit_action` DROP INDEX index_idsite_servertime;";
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();

    assert_eq!(
        result.translated_sql,
        "DROP INDEX \"matomo_log_link_visit_action_index_idsite_servertime\""
    );
    assert!(!result.translated_sql.contains("ALTER TABLE"));
}

#[test]
fn matomo_dimension_version_update_allows_mysql_type_text() {
    let sql = "UPDATE `matomo_option` SET option_value = 'INTEGER(10) UNSIGNED DEFAULT NULL', autoload = '1' WHERE option_name = 'version_log_link_visit_action.idaction_url'";
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();

    assert!(result
        .translated_sql
        .contains("\"matomo_option\" SET option_value = 'INTEGER(10) UNSIGNED DEFAULT NULL'"));
    assert!(result
        .translated_sql
        .contains("option_name = 'version_log_link_visit_action.idaction_url'"));
}

#[test]
fn create_table_with_desc_inline_key_translation_smoke() {
    let sql = r#"
        CREATE TABLE log_visit (
            idvisit BIGINT,
            idsite INT,
            config_id VARBINARY(16),
            visit_last_action_time DATETIME,
            idvisitor VARBINARY(8),
            KEY index_idsite_config_datetime (idsite, config_id, visit_last_action_time),
            KEY index_idsite_datetime (idsite, visit_last_action_time),
            KEY index_idsite_idvisitor_time (idsite, idvisitor, visit_last_action_time DESC)
        )
    "#;
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains(
        "CREATE INDEX \"log_visit_index_idsite_idvisitor_time\" ON \"log_visit\" (\"idsite\", \"idvisitor\", \"visit_last_action_time\" DESC)"
    ));
}

#[test]
fn create_table_with_unique_prefix_key_translation_smoke() {
    let sql = r#"
        CREATE TABLE log_profiling (
            query TEXT NOT NULL,
            count INTEGER UNSIGNED NULL,
            sum_time_ms FLOAT NULL,
            idprofiling BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            PRIMARY KEY (idprofiling),
            UNIQUE KEY query(query(100))
        )
    "#;
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("CREATE TABLE \"log_profiling\""));
    assert!(result
        .translated_sql
        .contains("CREATE UNIQUE INDEX \"log_profiling_query\" ON \"log_profiling\" ((left(\"query\", 100)))"));
}

#[test]
fn create_temporary_table_translation_smoke() {
    let sql = r#"
        CREATE TEMPORARY TABLE piwik_test_table_temp (
            id INT AUTO_INCREMENT,
            PRIMARY KEY (id)
        )
    "#;
    let result = translate_sql(sql, &TranslatorConfig::default()).unwrap();
    assert!(result.translated_sql.contains("CREATE TEMPORARY TABLE \"piwik_test_table_temp\""));
    assert!(result.translated_sql.contains("GENERATED BY DEFAULT AS IDENTITY"));
}
