#!/usr/bin/env bash
# Proves BookStack runs on PostgreSQL through the middleware.
#
#   docker compose --profile bookstack up -d --build
#   ./examples/bookstack/smoke.sh
#
# BookStack is a Laravel application and supports MySQL/MariaDB only, so its
# Eloquent queries are generated by Laravel's MySQL grammar throughout.
# The decisive checks are the last ones: rows written through Eloquent are read
# straight back out of PostgreSQL with psql.
set -uo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/../.."

SCHEMA="${BOOKSTACK_DB_NAME:-bookstack}"

failures=0
check() { # name expected actual
    if [[ "$3" == *"$2"* ]]; then printf '  ok   %s\n' "$1"
    else printf '  FAIL %s\n       expected to contain: %s\n       got: %s\n' "$1" "$2" "$3"; failures=$((failures+1)); fi
}
bs() { docker compose --profile bookstack run --rm -T -e BOOKSTACK_SKIP_MIGRATE=1 bookstack "$@" 2>&1; }
pg() { docker compose exec -T postgres psql -U postgres -d app -tAc "$1" 2>&1; }

echo "=== resetting the example schema ==="
docker compose exec -T postgres psql -U postgres -d app -q \
    -c "DROP SCHEMA IF EXISTS $SCHEMA CASCADE" >/dev/null 2>&1

echo
echo "=== migrations ==="
out="$(bs php artisan migrate --force --no-interaction)"
check "migrations run to completion"  "DONE"               "$out"
check "no migration failed"           ""                   "${out/FAIL/}"
check "the entity table is created"   "create_entities_table" "$out"

echo
echo "=== Eloquent write / read / aggregate ==="
out="$(bs php artisan mysql2pg:proof)"
check "rows created"                  "pages=3"           "$out"
check "aggregate SUM"                 "sum_priority=60"   "$out"
check "aggregate MAX"                 "max_priority=30"   "$out"
check "ORDER BY picks the right row"  "top=mysql2pg page three" "$out"
check "LIKE filter"                   "partial=mysql2pg page two" "$out"
check "UPDATE visible on re-read"     "updated=99"        "$out"
check "JOIN + GROUP BY"               "grouped=mysql2pg book/3"   "$out"
check "correlated subquery"           "subquery=3"        "$out"

echo
echo "=== the data is genuinely in PostgreSQL ==="
check "tables exist in PostgreSQL"    "entities" \
      "$(pg "SELECT tablename FROM pg_tables WHERE schemaname = '$SCHEMA' AND tablename = 'entities'")"
check "page count matches"            "3" \
      "$(pg "SELECT count(*) FROM $SCHEMA.entities WHERE type = 'page' AND name LIKE 'mysql2pg%'")"
check "updated value persisted"       "99" \
      "$(pg "SELECT priority FROM $SCHEMA.entities WHERE name = 'mysql2pg page three'")"
check "the book row is there"         "mysql2pg-book" \
      "$(pg "SELECT slug FROM $SCHEMA.entities WHERE slug = 'mysql2pg-book'")"
check "the role table was populated"  "1" \
      "$(pg "SELECT count(*) FROM $SCHEMA.roles WHERE system_name = 'admin'")"

echo
if (( failures )); then echo "$failures check(s) failed"; exit 1; fi
echo "all checks passed"
